# Site settings
title: Cris Hernández
description: Consultoría en ciencia de datos espaciales
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cris Hernandez
user_description: Consultor internacional en proyectos de ciencia de datos espaciales, ya sea para la obtención masiva de datos, arquitectura de datos, algoritmos y visualización.
user_title: Científico de datos
email: cris@crishernandez.co
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: crishernandezco
github_username:  crishernandezmaps
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com

exclude: ['package.json', 'src', 'node_modules', 'vendor']

